WARNING:root:Traceback (most recent call last):
  File "/home/jj/telegram_bot_simple/telebot/telebot.py", line 59, in background
    self.__onInlineQuery(u)
  File "/home/jj/telegram_bot_simple/telebot/telebot.py", line 211, in __onInlineQuery
    self.__api.answerInlineQueryEZ(u['inline_query']['id'],r,r)
  File "/home/jj/telegram_bot_simple/telebot/telegram_api.py", line 49, in answerInlineQueryEZ
    arr, arr[0]['id'] = [{'type':'article','message_text':text,'title':title}], id(arr)
UnboundLocalError: local variable 'arr' referenced before assignment

